version: '3.7'

services:
  app:
    build: ./
    ports:
      - "8091:8091"
    depends_on:
      - database
    environment:
      PORT: 8091
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5434/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:postgresql://database:5434/postgres
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres
  database:
    image: postgres:15-alpine
    container_name: postgres_diploma
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  #  app_frontend:
  #        image: orig-frontend:latest
  #        ports:
  #          - 8080:8080